// Configure your import map in config/importmap.rb. Read more: https://github.com/rails/importmap-rails
import "@hotwired/turbo-rails"
import "controllers"
import "./custom/dropdown"
import "./custom/new_booking"
import "./custom/edit_booking"
import "./custom/carousel"
import "./custom/modal"
import "./custom/rating_comment"
import "./custom/search_control"
import "popper"
import "bootstrap"
import "chartkick"
import "Chart.bundle"
import Highcharts from "highcharts"
window.Highcharts = Highcharts
