// Configure your import map in config/importmap.rb. Read more: https://github.com/rails/importmap-rails
import "@hotwired/turbo-rails"
import "controllers"
import "./custom/dropdown"
import "./custom/new_booking"
import "./custom/carousel"
import "./custom/choose_voucher"
import "./custom/rating_comment"
import "popper"
import "bootstrap"
